repos:
  - repo: local
    hooks:
      - id: trufflehog-docker
        name: TruffleHog (Docker)
        entry: bash -c 'docker run --rm -v "$(pwd):/pwd" -w /pwd trufflesecurity/trufflehog:latest filesystem . --fail --no-update --exclude-paths .trufflehog-ignore'
        language: system
        pass_filenames: false