repos:
  - repo: local
    hooks:
      - id: trufflehog-docker
        name: üê∑ TruffleHog (Secrets Scan)
        entry: bash -c 'docker run --rm -v "$(pwd):/pwd" trufflesecurity/trufflehog:latest filesystem /pwd --no-update --fail --exclude-paths /pwd/.trufflehog-ignore'
        language: system
        pass_filenames: false