repos:
  - repo: local
    hooks:
      - id: trufflehog-docker
        name: üê∑ TruffleHog (Secrets Scan)
        # Fix: Changed '--exclude-paths .trufflehog-ignore' to '/pwd/.trufflehog-ignore'
        entry: bash -c 'docker run --rm -v "$(pwd):/pwd" trufflesecurity/trufflehog:latest filesystem /pwd --no-update --fail --only-verified --exclude-paths /pwd/.trufflehog-ignore'
        language: system
        pass_filenames: false